export type StopType = "hub" | "university" | "hospital" | "shopping" | "residential";

export interface StopConfig {
  slug: string;
  citySlug: string;
  name: string;
  coords: { lat: number; lng: number };
  description: string;
  metaTitle: string;
  metaDescription: string;
  type: StopType;
}

export const STOPS: StopConfig[] = [
  // Helsinki (HSL) - 10 stops
  {
    slug: "rautatientori",
    citySlug: "helsinki",
    name: "Rautatientori",
    coords: { lat: 60.1712, lng: 24.9414 },
    description: "Rautatientori on Helsingin keskustan sydän ja tärkein joukkoliikenteen solmukohta. Täältä lähtee busseja, ratikoita ja metroja kaikkialle pääkaupunkiseudulle. Läheinen päärautatieasema yhdistää kauko- ja lähijunaliikenteen.",
    metaTitle: "Rautatientori Helsinki - Bussit, ratikat, metro ja junat reaaliajassa",
    metaDescription: "Katso Rautatientorin bussien, ratikoiden, metron ja junien aikataulut reaaliajassa. | Real-time buses, trams, metro & trains at Rautatientori.",
    type: "hub",
  },
  {
    slug: "kamppi",
    citySlug: "helsinki",
    name: "Kamppi",
    coords: { lat: 60.169, lng: 24.9324 },
    description: "Kamppi on Helsingin toiseksi vilkkain joukkoliikenneterminaali. Kampin keskuksen alta lähtee kaukobusseja ympäri Suomea sekä paikallisbusseja lähiöihin. Myös metro pysähtyy Kampissa.",
    metaTitle: "Kamppi Helsinki - Bussit ja metro reaaliajassa",
    metaDescription: "Katso Kampin bussiterminaalin ja metron aikataulut reaaliajassa. | Real-time buses & metro at Kamppi terminal.",
    type: "hub",
  },
  {
    slug: "hakaniemi",
    citySlug: "helsinki",
    name: "Hakaniemi",
    coords: { lat: 60.1797, lng: 24.9503 },
    description: "Hakaniemi on vilkas kaupunginosa Helsingin keskustan itäpuolella. Hakaniemen tori ja kauppahalli houkuttelevat asiakkaita, ja metroasema yhdistää alueen muuhun kaupunkiin.",
    metaTitle: "Hakaniemi Helsinki - Bussit, ratikat ja metro reaaliajassa",
    metaDescription: "Katso Hakaniemen bussien, ratikoiden ja metron aikataulut reaaliajassa. | Real-time buses, trams & metro at Hakaniemi.",
    type: "hub",
  },
  {
    slug: "pasila",
    citySlug: "helsinki",
    name: "Pasila",
    coords: { lat: 60.1986, lng: 24.9336 },
    description: "Pasila on merkittävä liikenteen solmukohta Helsingin pohjoispuolella. Pasilan asema palvelee lähijunia ja kaukojunia, ja alue on kehittynyt modernin toimistorakentamisen keskukseksi.",
    metaTitle: "Pasila Helsinki - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Pasilan aseman bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Pasila station.",
    type: "hub",
  },
  {
    slug: "itakeskus",
    citySlug: "helsinki",
    name: "Itäkeskus",
    coords: { lat: 60.2103, lng: 25.0826 },
    description: "Itäkeskus on Itä-Helsingin kaupallinen ja liikenteellinen keskus. Kauppakeskus Itis on Pohjoismaiden suurimpia, ja metroasema yhdistää alueen keskustaan.",
    metaTitle: "Itäkeskus Helsinki - Bussit ja metro reaaliajassa",
    metaDescription: "Katso Itäkeskuksen bussien ja metron aikataulut reaaliajassa. | Real-time buses & metro at Itäkeskus.",
    type: "hub",
  },
  {
    slug: "kallio",
    citySlug: "helsinki",
    name: "Kallio",
    coords: { lat: 60.1842, lng: 24.9496 },
    description: "Kallio on Helsingin trendikkäin kaupunginosa, tunnettu ravintoloistaan ja yöelämästään. Kallion kirkko hallitsee maisemaa, ja alueen läpi kulkee useita bussi- ja ratikkalinjoja.",
    metaTitle: "Kallio Helsinki - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Kallion bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams in Kallio.",
    type: "residential",
  },
  {
    slug: "lauttasaari",
    citySlug: "helsinki",
    name: "Lauttasaari",
    coords: { lat: 60.1572, lng: 24.8773 },
    description: "Lauttasaari on suosittu asuinalue Helsingin länsipuolella. Saari on yhdistetty mantereeseen sillalla, ja metro sekä bussit palvelevat aluetta hyvin.",
    metaTitle: "Lauttasaari Helsinki - Bussit ja metro reaaliajassa",
    metaDescription: "Katso Lauttasaaren bussien ja metron aikataulut reaaliajassa. | Real-time buses & metro at Lauttasaari.",
    type: "residential",
  },
  {
    slug: "leppavaara",
    citySlug: "helsinki",
    name: "Leppävaara",
    coords: { lat: 60.2195, lng: 24.8131 },
    description: "Leppävaara on Espoon suurin alakeskus ja vilkas kaupallinen keskittymä. Sello-kauppakeskus ja juna-asema tekevät alueesta tärkeän joukkoliikenteen solmukohdan.",
    metaTitle: "Leppävaara Espoo - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Leppävaaran bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Leppävaara.",
    type: "hub",
  },
  {
    slug: "tapiola",
    citySlug: "helsinki",
    name: "Tapiola",
    coords: { lat: 60.1762, lng: 24.8046 },
    description: "Tapiola on Espoon perinteinen keskus, tunnettu puutarhakaupunkisuunnittelustaan. Metroasema ja bussiterminaali yhdistävät Tapiolan muuhun pääkaupunkiseutuun.",
    metaTitle: "Tapiola Espoo - Bussit ja metro reaaliajassa",
    metaDescription: "Katso Tapiolan bussien ja metron aikataulut reaaliajassa. | Real-time buses & metro at Tapiola.",
    type: "hub",
  },
  {
    slug: "malmi",
    citySlug: "helsinki",
    name: "Malmi",
    coords: { lat: 60.2512, lng: 25.0093 },
    description: "Malmi on Koillis-Helsingin keskus ja vilkas kaupallinen alue. Malmin juna-asema ja bussiterminaali palvelevat laajaa aluetta Pohjois- ja Itä-Helsingissä.",
    metaTitle: "Malmi Helsinki - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Malmin bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Malmi station.",
    type: "hub",
  },

  // Tampere (Nysse) - 10 stops
  {
    slug: "keskustori",
    citySlug: "tampere",
    name: "Keskustori",
    coords: { lat: 61.4978, lng: 23.761 },
    description: "Keskustori on Tampereen sydän ja joukkoliikenteen keskipiste. Historiallinen tori on ympäröity kaupoilla ja kahviloilla, ja raitiotie sekä bussit kulkevat torin läpi.",
    metaTitle: "Keskustori Tampere - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Keskustorin bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams at Keskustori.",
    type: "hub",
  },
  {
    slug: "rautatieasema",
    citySlug: "tampere",
    name: "Rautatieasema",
    coords: { lat: 61.4986, lng: 23.773 },
    description: "Tampereen rautatieasema on maan kolmanneksi vilkkain. Asemalta lähtee junia Helsinkiin, Turkuun, Ouluun ja Poriin. Raitiotie ja bussit yhdistävät aseman keskustaan.",
    metaTitle: "Rautatieasema Tampere - Bussit, ratikat ja junat reaaliajassa",
    metaDescription: "Katso Tampereen rautatieaseman bussien, ratikoiden ja junien aikataulut reaaliajassa. | Real-time buses, trams & trains at Tampere station.",
    type: "hub",
  },
  {
    slug: "hervanta",
    citySlug: "tampere",
    name: "Hervanta",
    coords: { lat: 61.4503, lng: 23.8512 },
    description: "Hervanta on Tampereen suurin lähiö ja teknologiakeskittymä. Tampereen yliopiston Hervannan kampus ja TTY sijaitsevat täällä. Raitiotie yhdistää Hervannan keskustaan.",
    metaTitle: "Hervanta Tampere - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Hervannan bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams at Hervanta.",
    type: "residential",
  },
  {
    slug: "tays",
    citySlug: "tampere",
    name: "TAYS sairaala",
    coords: { lat: 61.5047, lng: 23.8169 },
    description: "Tampereen yliopistollinen sairaala (TAYS) on yksi Suomen suurimmista sairaaloista. Raitiotie ja useat bussilinjat palvelevat sairaalaa ja sen henkilökuntaa ja potilaita.",
    metaTitle: "TAYS Tampere - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Taysin sairaalan bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams at TAYS hospital.",
    type: "hospital",
  },
  {
    slug: "ratina",
    citySlug: "tampere",
    name: "Ratina",
    coords: { lat: 61.4928, lng: 23.7716 },
    description: "Ratina on Tampereen moderni kauppakeskus ja stadionalue. Ratinan stadion isännöi jalkapallo-otteluita ja konsertteja. Raitiotie ja bussit pysähtyvät Ratinassa.",
    metaTitle: "Ratina Tampere - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Ratinan bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams at Ratina.",
    type: "shopping",
  },
  {
    slug: "kaleva",
    citySlug: "tampere",
    name: "Kaleva",
    coords: { lat: 61.493, lng: 23.8059 },
    description: "Kaleva on suosittu asuinalue Tampereen itäpuolella. Kalevan kirkko on alueen maamerkki. Bussit ja raitiotie yhdistävät Kalevan keskustaan ja muihin kaupunginosiin.",
    metaTitle: "Kaleva Tampere - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Kalevan bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams in Kaleva.",
    type: "residential",
  },
  {
    slug: "lielahti",
    citySlug: "tampere",
    name: "Lielahti",
    coords: { lat: 61.5104, lng: 23.6981 },
    description: "Lielahti on Tampereen lännen kaupallinen keskus, tunnettu Ideapark-kauppakeskuksestaan. Alue on kasvanut merkittäväksi ostoskohteeksi hyvien liikenneyhteyksien ansiosta.",
    metaTitle: "Lielahti Tampere - Bussit reaaliajassa",
    metaDescription: "Katso Lielahden ja Ideaparkin bussien aikataulut reaaliajassa. | Real-time buses at Lielahti.",
    type: "shopping",
  },
  {
    slug: "yliopisto",
    citySlug: "tampere",
    name: "Tampereen yliopisto",
    coords: { lat: 61.4942, lng: 23.7794 },
    description: "Tampereen yliopiston keskustakampus sijaitsee aivan keskustan tuntumassa. Kampus on vilkas opiskelijakeskittymä, ja raitiotie kulkee yliopiston ohi.",
    metaTitle: "Tampereen yliopisto - Bussit ja ratikat reaaliajassa",
    metaDescription: "Katso Tampereen yliopiston bussien ja ratikoiden aikataulut reaaliajassa. | Real-time buses & trams at Tampere University.",
    type: "university",
  },
  {
    slug: "lentavanniemi",
    citySlug: "tampere",
    name: "Lentävänniemi",
    coords: { lat: 61.5178, lng: 23.6619 },
    description: "Lentävänniemi on Tampereen luoteinen asuinalue Näsijärven rannalla. Alue on rauhallinen ja luonnonläheinen, ja bussiyhteydet keskustaan ovat hyvät.",
    metaTitle: "Lentävänniemi Tampere - Bussit reaaliajassa",
    metaDescription: "Katso Lentävänniemen bussien aikataulut reaaliajassa. | Real-time buses at Lentävänniemi.",
    type: "residential",
  },
  {
    slug: "hatanpaa",
    citySlug: "tampere",
    name: "Hatanpää",
    coords: { lat: 61.4836, lng: 23.7882 },
    description: "Hatanpää on historiallinen alue Tampereen eteläpuolella. Hatanpään arboretum ja kartano ovat suosittuja vierailukohteita. Bussit palvelevat aluetta säännöllisesti.",
    metaTitle: "Hatanpää Tampere - Bussit reaaliajassa",
    metaDescription: "Katso Hatanpään bussien aikataulut reaaliajassa. | Real-time buses at Hatanpää.",
    type: "residential",
  },

  // Turku (Föli) - 10 stops
  {
    slug: "kauppatori",
    citySlug: "turku",
    name: "Kauppatori",
    coords: { lat: 60.4518, lng: 22.2666 },
    description: "Kauppatori on Turun keskustan sydän ja joukkoliikenteen solmukohta. Historiallinen tori on ympäröity kaupoilla ja nähtävyyksillä. Lähes kaikki bussilinjat kulkevat torin kautta.",
    metaTitle: "Kauppatori Turku - Bussit reaaliajassa",
    metaDescription: "Katso Kauppatorin bussien aikataulut reaaliajassa. Turun joukkoliikenteen solmukohta. | Real-time buses at Turku Market Square.",
    type: "hub",
  },
  {
    slug: "kupittaa",
    citySlug: "turku",
    name: "Kupittaa",
    coords: { lat: 60.4485, lng: 22.2952 },
    description: "Kupittaa on Turun itäinen keskus, tunnettu Kupittaan puistosta ja teknologiakeskittymästä. Juna-asema ja bussit yhdistävät alueen muuhun kaupunkiin.",
    metaTitle: "Kupittaa Turku - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Kupittaan bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Kupittaa.",
    type: "hub",
  },
  {
    slug: "satama",
    citySlug: "turku",
    name: "Turun satama",
    coords: { lat: 60.435, lng: 22.2215 },
    description: "Turun satama on Suomen vilkkain matkustajasatama Ruotsiin. Viking Line ja Tallink Silja liikennöivät päivittäin. Bussit kuljettavat matkustajia satamaan ja keskustaan.",
    metaTitle: "Turun satama - Bussit reaaliajassa",
    metaDescription: "Katso Turun sataman bussien aikataulut reaaliajassa. Suomen vilkkain matkustajasatama.",
    type: "hub",
  },
  {
    slug: "yliopisto",
    citySlug: "turku",
    name: "Turun yliopisto",
    coords: { lat: 60.4539, lng: 22.286 },
    description: "Turun yliopisto on Suomen toiseksi vanhin yliopisto. Kampus sijaitsee keskustan tuntumassa, ja useat bussilinjat palvelevat opiskelijoita.",
    metaTitle: "Turun yliopisto - Bussit reaaliajassa",
    metaDescription: "Katso Turun yliopiston bussien aikataulut reaaliajassa. Yliopistokampuksen joukkoliikenne.",
    type: "university",
  },
  {
    slug: "skanssi",
    citySlug: "turku",
    name: "Skanssi",
    coords: { lat: 60.4273, lng: 22.274 },
    description: "Skanssi on Turun eteläinen kauppakeskittymä. Skanssin kauppakeskus tarjoaa monipuoliset ostomahdollisuudet, ja bussit kulkevat keskustasta säännöllisesti.",
    metaTitle: "Skanssi Turku - Bussit reaaliajassa",
    metaDescription: "Katso Skanssin kauppakeskuksen bussien aikataulut reaaliajassa. Turun eteläinen ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "varissuo",
    citySlug: "turku",
    name: "Varissuo",
    coords: { lat: 60.4692, lng: 22.343 },
    description: "Varissuo on monikulttuurinen asuinalue Turun koillisosassa. Alue on tunnettu vilkkaasta torielämästään, ja bussit yhdistävät Varissuon keskustaan.",
    metaTitle: "Varissuo Turku - Bussit reaaliajassa",
    metaDescription: "Katso Varissuon bussien aikataulut reaaliajassa. Turun koillinen kaupunginosa.",
    type: "residential",
  },
  {
    slug: "runosmaki",
    citySlug: "turku",
    name: "Runosmäki",
    coords: { lat: 60.4737, lng: 22.2271 },
    description: "Runosmäki on 1970-luvulla rakennettu asuinalue Turun pohjoisosassa. Alue on rauhallinen ja perheystävällinen, ja bussit kulkevat keskustaan säännöllisesti.",
    metaTitle: "Runosmäki Turku - Bussit reaaliajassa",
    metaDescription: "Katso Runosmäen bussien aikataulut reaaliajassa. Turun pohjoinen asuinalue.",
    type: "residential",
  },
  {
    slug: "lansikeskus",
    citySlug: "turku",
    name: "Länsikeskus",
    coords: { lat: 60.451, lng: 22.2101 },
    description: "Länsikeskus on Turun läntinen kauppakeskittymä sataman läheisyydessä. Alue palvelee sekä paikallisia asukkaita että satamaan matkustavia.",
    metaTitle: "Länsikeskus Turku - Bussit reaaliajassa",
    metaDescription: "Katso Länsikeskuksen bussien aikataulut reaaliajassa. Turun läntinen kauppakeskus.",
    type: "shopping",
  },
  {
    slug: "raunistula",
    citySlug: "turku",
    name: "Raunistula",
    coords: { lat: 60.463, lng: 22.2346 },
    description: "Raunistula on perinteinen asuinalue Turun keskustan pohjoispuolella. Alue on rauhallinen ja hyvin saavutettavissa bussilla.",
    metaTitle: "Raunistula Turku - Bussit reaaliajassa",
    metaDescription: "Katso Raunistulan bussien aikataulut reaaliajassa. Turun pohjoinen asuinalue.",
    type: "residential",
  },
  {
    slug: "nummi",
    citySlug: "turku",
    name: "Nummi",
    coords: { lat: 60.44, lng: 22.237 },
    description: "Nummi on vanha työläiskaupunginosa Turun keskustan eteläpuolella. Alue on säilyttänyt perinteisen ilmeensä ja on hyvin bussiliikenteen saavutettavissa.",
    metaTitle: "Nummi Turku - Bussit reaaliajassa",
    metaDescription: "Katso Nummen bussien aikataulut reaaliajassa. Turun perinteinen kaupunginosa.",
    type: "residential",
  },

  // Oulu (OSL) - 10 stops
  {
    slug: "keskusta",
    citySlug: "oulu",
    name: "Keskusta",
    coords: { lat: 65.0121, lng: 25.4651 },
    description: "Oulun keskusta on pohjoisen Suomen vilkkain kaupunkikeskus. Rotuaari-kävelykatu ja tori ovat alueen sydän. Bussit lähtevät keskustasta kaikkialle Ouluun.",
    metaTitle: "Oulu keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Oulun keskustan bussien aikataulut reaaliajassa. | Real-time buses in Oulu city center.",
    type: "hub",
  },
  {
    slug: "rautatieasema",
    citySlug: "oulu",
    name: "Rautatieasema",
    coords: { lat: 65.0116, lng: 25.483 },
    description: "Oulun rautatieasema on Pohjois-Suomen tärkein junaliikenteen solmukohta. Asemalta lähtee junia etelään ja pohjoiseen, ja bussit yhdistävät aseman keskustaan.",
    metaTitle: "Oulun rautatieasema - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Oulun rautatieaseman bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Oulu station.",
    type: "hub",
  },
  {
    slug: "tuira",
    citySlug: "oulu",
    name: "Tuira",
    coords: { lat: 65.0246, lng: 25.4683 },
    description: "Tuira on vanha työläiskaupunginosa Oulun keskustan pohjoispuolella. Merikosken voimalaitos ja Hupisaaret-puisto ovat alueen maamerkkejä.",
    metaTitle: "Tuira Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Tuiran bussien aikataulut reaaliajassa. Oulun pohjoinen kaupunginosa.",
    type: "residential",
  },
  {
    slug: "linnanmaa",
    citySlug: "oulu",
    name: "Linnanmaa",
    coords: { lat: 65.0587, lng: 25.4666 },
    description: "Linnanmaa on Oulun yliopiston kampusalue kaupungin pohjoispuolella. Alue on vilkas opiskelijakeskittymä, ja bussit kulkevat keskustaan tiheästi.",
    metaTitle: "Linnanmaa Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Linnanmaan yliopistokampuksen bussien aikataulut. Oulun yliopiston joukkoliikenne.",
    type: "university",
  },
  {
    slug: "kontinkangas",
    citySlug: "oulu",
    name: "Kontinkangas",
    coords: { lat: 65.0072, lng: 25.5133 },
    description: "Kontinkangas on Oulun sairaala-alue, jossa sijaitsee Oulun yliopistollinen sairaala (OYS). Bussit palvelevat sairaalaa ja sen henkilökuntaa ympäri vuorokauden.",
    metaTitle: "Kontinkangas Oulu - Bussit reaaliajassa",
    metaDescription: "Katso OYS:n sairaala-alueen bussien aikataulut. Oulun yliopistollisen sairaalan joukkoliikenne.",
    type: "hospital",
  },
  {
    slug: "kaakkuri",
    citySlug: "oulu",
    name: "Kaakkuri",
    coords: { lat: 64.9965, lng: 25.4282 },
    description: "Kaakkuri on Oulun eteläinen kauppakeskittymä. Zeppelin-kauppakeskus ja muut liikkeet tekevät alueesta suositun ostoskohteen.",
    metaTitle: "Kaakkuri Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Kaakkurin kauppakeskuksen bussien aikataulut. Oulun eteläinen ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "raksila",
    citySlug: "oulu",
    name: "Raksila",
    coords: { lat: 65.0015, lng: 25.4803 },
    description: "Raksila on urheilu- ja tapahtumakeskus Oulun keskustan itäpuolella. Raatin stadion ja jäähalli sijaitsevat täällä. Bussit kulkevat Raksilaan keskustasta.",
    metaTitle: "Raksila Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Raksilan urheilukeskuksen bussien aikataulut. Oulun tapahtumakeskus.",
    type: "hub",
  },
  {
    slug: "kaukovainio",
    citySlug: "oulu",
    name: "Kaukovainio",
    coords: { lat: 65.0214, lng: 25.5102 },
    description: "Kaukovainio on itäinen asuinalue Oulussa, lähellä yliopistollista sairaalaa. Alue on rauhallinen ja perheystävällinen.",
    metaTitle: "Kaukovainio Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Kaukovainion bussien aikataulut reaaliajassa. Oulun itäinen asuinalue.",
    type: "residential",
  },
  {
    slug: "pateniemi",
    citySlug: "oulu",
    name: "Pateniemi",
    coords: { lat: 65.0532, lng: 25.4292 },
    description: "Pateniemi on merenrantakaupunginosa Oulun pohjoisosassa. Alue tunnetaan kauniista merimaisemistaan ja rauhallisesta tunnelmastaan.",
    metaTitle: "Pateniemi Oulu - Bussit reaaliajassa",
    metaDescription: "Katso Pateniemen bussien aikataulut reaaliajassa. Oulun pohjoinen merenrantakaupunginosa.",
    type: "residential",
  },
  {
    slug: "oulunsalo",
    citySlug: "oulu",
    name: "Oulunsalo",
    coords: { lat: 64.9401, lng: 25.4128 },
    description: "Oulunsalo on entinen itsenäinen kunta, nykyään osa Oulua. Oulun lentoasema sijaitsee täällä. Bussit yhdistävät Oulunsalon keskustaan.",
    metaTitle: "Oulunsalo - Bussit ja lentokenttä reaaliajassa",
    metaDescription: "Katso Oulunsalon ja lentoaseman bussien aikataulut. Oulun eteläinen alue.",
    type: "residential",
  },

  // Jyväskylä (Linkki) - 10 stops
  {
    slug: "matkakeskus",
    citySlug: "jyvaskyla",
    name: "Matkakeskus",
    coords: { lat: 62.2426, lng: 25.7473 },
    description: "Jyväskylän matkakeskus yhdistää bussi- ja junaliikenteen. Asemalta lähtee kaukobusseja ympäri Suomea ja paikallisbusseja koko Jyväskylän seudulle.",
    metaTitle: "Jyväskylän matkakeskus - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Jyväskylän matkakeskuksen bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Jyväskylä Travel Centre.",
    type: "hub",
  },
  {
    slug: "keskusta",
    citySlug: "jyvaskyla",
    name: "Keskusta",
    coords: { lat: 62.2417, lng: 25.7466 },
    description: "Jyväskylän keskusta on Keski-Suomen vilkkain kaupunkikeskus. Kävelykatu ja kauppakeskukset houkuttelevat asiakkaita, ja bussit kulkevat keskustan läpi.",
    metaTitle: "Jyväskylän keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Jyväskylän keskustan bussien aikataulut reaaliajassa. Keski-Suomen pääkaupunki.",
    type: "hub",
  },
  {
    slug: "yliopisto",
    citySlug: "jyvaskyla",
    name: "Jyväskylän yliopisto",
    coords: { lat: 62.2315, lng: 25.7368 },
    description: "Jyväskylän yliopisto on Keski-Suomen suurin yliopisto, tunnettu erityisesti liikuntatieteistä ja kasvatustieteistä. Kampus sijaitsee järven rannalla.",
    metaTitle: "Jyväskylän yliopisto - Bussit reaaliajassa",
    metaDescription: "Katso Jyväskylän yliopiston bussien aikataulut. Yliopistokampuksen joukkoliikenne.",
    type: "university",
  },
  {
    slug: "kuokkala",
    citySlug: "jyvaskyla",
    name: "Kuokkala",
    coords: { lat: 62.2166, lng: 25.7206 },
    description: "Kuokkala on suosittu asuinalue Jyväskylän eteläosassa. Alue tunnetaan Kuokkalan sillasta ja aktiivisesta asukasyhteisöstä.",
    metaTitle: "Kuokkala Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Kuokkalan bussien aikataulut reaaliajassa. Jyväskylän eteläinen asuinalue.",
    type: "residential",
  },
  {
    slug: "palokka",
    citySlug: "jyvaskyla",
    name: "Palokka",
    coords: { lat: 62.2893, lng: 25.7621 },
    description: "Palokka on nopeasti kasvava asuinalue Jyväskylän pohjoispuolella. Alue tarjoaa hyvät palvelut ja bussiyhteydet keskustaan.",
    metaTitle: "Palokka Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Palokan bussien aikataulut reaaliajassa. Jyväskylän pohjoinen kasvukeskus.",
    type: "residential",
  },
  {
    slug: "keljo",
    citySlug: "jyvaskyla",
    name: "Keljo",
    coords: { lat: 62.2316, lng: 25.6823 },
    description: "Keljo on kauppakeskittymä Jyväskylän länsipuolella. Prisma ja muut liikkeet tekevät alueesta suositun ostoskohteen.",
    metaTitle: "Keljo Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Keljon kauppakeskuksen bussien aikataulut. Jyväskylän läntinen ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "seppala",
    citySlug: "jyvaskyla",
    name: "Seppälä",
    coords: { lat: 62.2605, lng: 25.7628 },
    description: "Seppälä on Jyväskylän suurin kauppakeskittymä. Seppälän marketalue ja Prisma houkuttelevat asiakkaita koko seudulta.",
    metaTitle: "Seppälä Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Seppälän kauppakeskuksen bussien aikataulut. Jyväskylän suurin ostosalue.",
    type: "shopping",
  },
  {
    slug: "vaajakoski",
    citySlug: "jyvaskyla",
    name: "Vaajakoski",
    coords: { lat: 62.2506, lng: 25.8672 },
    description: "Vaajakoski on itäinen taajama, entinen itsenäinen kunta. Alue tunnetaan teollisuushistoriastaan ja urheiluseuroistaan.",
    metaTitle: "Vaajakoski Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Vaajakosken bussien aikataulut reaaliajassa. Jyväskylän itäinen taajama.",
    type: "residential",
  },
  {
    slug: "kortepohja",
    citySlug: "jyvaskyla",
    name: "Kortepohja",
    coords: { lat: 62.2134, lng: 25.7536 },
    description: "Kortepohja on opiskelijakaupunginosa yliopiston läheisyydessä. KOAS-opiskelijatalot sijaitsevat täällä, ja bussit kulkevat keskustaan tiheästi.",
    metaTitle: "Kortepohja Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Kortepohjan bussien aikataulut. Jyväskylän opiskelijakaupunginosa.",
    type: "residential",
  },
  {
    slug: "taulumaki",
    citySlug: "jyvaskyla",
    name: "Taulumäki",
    coords: { lat: 62.2509, lng: 25.7193 },
    description: "Taulumäki on perinteinen asuinalue Jyväskylän keskustan länsipuolella. Alue on rauhallinen ja hyvin saavutettavissa bussilla.",
    metaTitle: "Taulumäki Jyväskylä - Bussit reaaliajassa",
    metaDescription: "Katso Taulumäen bussien aikataulut reaaliajassa. Jyväskylän läntinen asuinalue.",
    type: "residential",
  },

  // Lahti (LSL) - 10 stops
  {
    slug: "matkakeskus",
    citySlug: "lahti",
    name: "Matkakeskus",
    coords: { lat: 60.9827, lng: 25.6556 },
    description: "Lahden matkakeskus on kaupungin liikenteen solmukohta, jossa yhdistyvät juna- ja bussiliikenne. Asemalta pääsee nopeasti Helsinkiin ja ympäri Päijät-Hämettä.",
    metaTitle: "Lahden matkakeskus - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Lahden matkakeskuksen bussien ja junien aikataulut reaaliajassa. | Real-time buses & trains at Lahti Travel Centre.",
    type: "hub",
  },
  {
    slug: "keskusta",
    citySlug: "lahti",
    name: "Keskusta",
    coords: { lat: 60.9839, lng: 25.6551 },
    description: "Lahden keskusta on Päijät-Hämeen kaupallinen sydän. Aleksanterinkatu ja torikeskus houkuttelevat asiakkaita, ja bussit kulkevat keskustan läpi.",
    metaTitle: "Lahden keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Lahden keskustan bussien aikataulut reaaliajassa. Päijät-Hämeen pääkaupunki.",
    type: "hub",
  },
  {
    slug: "trio",
    citySlug: "lahti",
    name: "Trio",
    coords: { lat: 60.9849, lng: 25.6642 },
    description: "Trio on Lahden suurin kauppakeskus aivan keskustan tuntumassa. Monipuoliset liikkeet ja ravintolat palvelevat asiakkaita.",
    metaTitle: "Trio Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Trion kauppakeskuksen bussien aikataulut. Lahden suurin ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "salpausselka",
    citySlug: "lahti",
    name: "Salpausselkä",
    coords: { lat: 60.973, lng: 25.6486 },
    description: "Salpausselkä on Lahden urheilukeskus, tunnettu hiihtoladuistaan ja hyppyrimäistään. Lahti Ski Games järjestetään täällä vuosittain.",
    metaTitle: "Salpausselkä Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Salpausselän urheilukeskuksen bussien aikataulut. Lahden hiihtostadion.",
    type: "hub",
  },
  {
    slug: "mukkula",
    citySlug: "lahti",
    name: "Mukkula",
    coords: { lat: 61.0043, lng: 25.6863 },
    description: "Mukkula on suuri asuinalue Lahden koillisosassa Vesijärven rannalla. Mukkulan kartano ja uimaranta ovat alueen nähtävyyksiä.",
    metaTitle: "Mukkula Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Mukkulan bussien aikataulut reaaliajassa. Lahden koillinen asuinalue.",
    type: "residential",
  },
  {
    slug: "launeen-keskus",
    citySlug: "lahti",
    name: "Launeen keskus",
    coords: { lat: 60.9761, lng: 25.6203 },
    description: "Laune on läntinen asuinalue Lahdessa. Launeen perhepuisto on suosittu vierailukohde perheille.",
    metaTitle: "Laune Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Launeen bussien aikataulut reaaliajassa. Lahden läntinen asuinalue.",
    type: "residential",
  },
  {
    slug: "askonalue",
    citySlug: "lahti",
    name: "Askonalue",
    coords: { lat: 60.9956, lng: 25.6296 },
    description: "Askonalue on entinen teollisuusalue, joka on muuttunut modernin asumisen ja kulttuurin keskukseksi. Sibeliustalo sijaitsee lähistöllä.",
    metaTitle: "Askonalue Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Askonalueen bussien aikataulut. Lahden kulttuuri- ja asuinalue.",
    type: "residential",
  },
  {
    slug: "paijat-hame-keskussairaala",
    citySlug: "lahti",
    name: "Päijät-Häme keskussairaala",
    coords: { lat: 60.9916, lng: 25.6021 },
    description: "Päijät-Hämeen keskussairaala on alueen suurin sairaala. Bussit palvelevat sairaalaa ja sen henkilökuntaa säännöllisesti.",
    metaTitle: "PHKS Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Päijät-Hämeen keskussairaalan bussien aikataulut. Lahden sairaala-alue.",
    type: "hospital",
  },
  {
    slug: "jalkaranta",
    citySlug: "lahti",
    name: "Jalkaranta",
    coords: { lat: 60.9947, lng: 25.6648 },
    description: "Jalkaranta on itäinen asuinalue Lahden keskustan pohjoispuolella. Alue on rauhallinen ja perheystävällinen.",
    metaTitle: "Jalkaranta Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Jalkarannan bussien aikataulut reaaliajassa. Lahden itäinen asuinalue.",
    type: "residential",
  },
  {
    slug: "karisto",
    citySlug: "lahti",
    name: "Karisto",
    coords: { lat: 60.9545, lng: 25.5955 },
    description: "Karisto on uusi asuinalue Lahden eteläpuolella. Alue on suunniteltu ekologiseksi ja perheystävälliseksi.",
    metaTitle: "Karisto Lahti - Bussit reaaliajassa",
    metaDescription: "Katso Kariston bussien aikataulut reaaliajassa. Lahden eteläinen uusi asuinalue.",
    type: "residential",
  },

  // Kuopio (Vilkku) - 10 stops
  {
    slug: "keskusta",
    citySlug: "kuopio",
    name: "Keskusta",
    coords: { lat: 62.8925, lng: 27.6783 },
    description: "Kuopion keskusta on Itä-Suomen vilkkain kaupunkikeskus. Tori ja kauppahalli ovat alueen sydän, ja bussit lähtevät keskustasta kaikkialle.",
    metaTitle: "Kuopion keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Kuopion keskustan bussien aikataulut reaaliajassa. | Real-time buses in Kuopio city center.",
    type: "hub",
  },
  {
    slug: "matkakeskus",
    citySlug: "kuopio",
    name: "Matkakeskus",
    coords: { lat: 62.8978, lng: 27.6799 },
    description: "Kuopion matkakeskus yhdistää bussi- ja junaliikenteen. Asemalta lähtee junia Helsinkiin ja kaukobusseja ympäri Suomea.",
    metaTitle: "Kuopion matkakeskus - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Kuopion matkakeskuksen bussien ja junien aikataulut. Itä-Suomen liikenteen solmukohta.",
    type: "hub",
  },
  {
    slug: "savilahti",
    citySlug: "kuopio",
    name: "Savilahti",
    coords: { lat: 62.8996, lng: 27.639 },
    description: "Savilahti on Kuopion yliopistokampus ja teknologiakeskittymä. Itä-Suomen yliopiston Kuopion kampus sijaitsee täällä.",
    metaTitle: "Savilahti Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Savilahden yliopistokampuksen bussien aikataulut. Kuopion yliopisto.",
    type: "university",
  },
  {
    slug: "petonen",
    citySlug: "kuopio",
    name: "Petonen",
    coords: { lat: 62.853, lng: 27.6545 },
    description: "Petonen on Kuopion eteläinen asuinalue. Alue on kasvanut nopeasti ja tarjoaa hyvät palvelut ja bussiyhteydet.",
    metaTitle: "Petonen Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Petosen bussien aikataulut reaaliajassa. Kuopion eteläinen asuinalue.",
    type: "residential",
  },
  {
    slug: "saaristokaupunki",
    citySlug: "kuopio",
    name: "Saaristokaupunki",
    coords: { lat: 62.882, lng: 27.725 },
    description: "Saaristokaupunki on uusi asuinalue Kallaveden saarilla. Alue on moderni ja ekologinen, ja bussit yhdistävät sen keskustaan.",
    metaTitle: "Saaristokaupunki Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Saaristokaupungin bussien aikataulut. Kuopion uusi järvenranta-asuinalue.",
    type: "residential",
  },
  {
    slug: "puijonlaakso",
    citySlug: "kuopio",
    name: "Puijonlaakso",
    coords: { lat: 62.911, lng: 27.6565 },
    description: "Puijonlaakso sijaitsee kuuluisan Puijon tornin juurella. Alue on suosittu niin asukkaiden kuin turistienkin keskuudessa.",
    metaTitle: "Puijonlaakso Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Puijonlaakson bussien aikataulut. Puijon tornin läheinen asuinalue.",
    type: "residential",
  },
  {
    slug: "kys",
    citySlug: "kuopio",
    name: "KYS sairaala",
    coords: { lat: 62.879, lng: 27.638 },
    description: "Kuopion yliopistollinen sairaala (KYS) on Itä-Suomen suurin sairaala. Bussit palvelevat sairaalaa ja sen henkilökuntaa ympäri vuorokauden.",
    metaTitle: "KYS Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Kuopion yliopistollisen sairaalan bussien aikataulut. KYS:n joukkoliikenne.",
    type: "hospital",
  },
  {
    slug: "levasen",
    citySlug: "kuopio",
    name: "Leväsen",
    coords: { lat: 62.9035, lng: 27.714 },
    description: "Levänen on itäinen asuinalue Kuopiossa. Alue on rauhallinen ja hyvin bussiliikenteen saavutettavissa.",
    metaTitle: "Leväsen Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Leväsen bussien aikataulut reaaliajassa. Kuopion itäinen asuinalue.",
    type: "residential",
  },
  {
    slug: "mantyharjunkatu",
    citySlug: "kuopio",
    name: "Mäntyharju",
    coords: { lat: 62.876, lng: 27.655 },
    description: "Mäntyharju on perinteinen asuinalue Kuopion keskustan eteläpuolella. Alue on hyvin saavutettavissa bussilla.",
    metaTitle: "Mäntyharju Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Mäntyharjun bussien aikataulut reaaliajassa. Kuopion eteläinen kaupunginosa.",
    type: "residential",
  },
  {
    slug: "pihlajalaakso",
    citySlug: "kuopio",
    name: "Pihlajalaakso",
    coords: { lat: 62.8689, lng: 27.696 },
    description: "Pihlajalaakso on kaakkoinen asuinalue Kuopiossa. Alue on rauhallinen ja perheystävällinen.",
    metaTitle: "Pihlajalaakso Kuopio - Bussit reaaliajassa",
    metaDescription: "Katso Pihlajalaakson bussien aikataulut reaaliajassa. Kuopion kaakkoinen asuinalue.",
    type: "residential",
  },

  // Lappeenranta (Jouko) - 10 stops
  {
    slug: "keskusta",
    citySlug: "lappeenranta",
    name: "Keskusta",
    coords: { lat: 61.0587, lng: 28.1887 },
    description: "Lappeenrannan keskusta sijaitsee Saimaan rannalla. Kauppakadut ja satama-alue houkuttelevat niin paikallisia kuin turistejakin.",
    metaTitle: "Lappeenrannan keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Lappeenrannan keskustan bussien aikataulut reaaliajassa. | Real-time buses in Lappeenranta city center.",
    type: "hub",
  },
  {
    slug: "matkakeskus",
    citySlug: "lappeenranta",
    name: "Matkakeskus",
    coords: { lat: 61.047, lng: 28.2065 },
    description: "Lappeenrannan matkakeskus yhdistää bussi- ja junaliikenteen. Asemalta lähtee junia Helsinkiin ja busseja ympäri Etelä-Karjalaa.",
    metaTitle: "Lappeenrannan matkakeskus - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Lappeenrannan matkakeskuksen bussien ja junien aikataulut.",
    type: "hub",
  },
  {
    slug: "skinnarila",
    citySlug: "lappeenranta",
    name: "Skinnarila",
    coords: { lat: 61.0649, lng: 28.0945 },
    description: "Skinnarila on LUT-yliopiston kampusalue. Lappeenrannan teknillinen yliopisto on tunnettu energia- ja ympäristötekniikastaan.",
    metaTitle: "Skinnarila Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso LUT-yliopiston Skinnarilan kampuksen bussien aikataulut.",
    type: "university",
  },
  {
    slug: "sammonlahti",
    citySlug: "lappeenranta",
    name: "Sammonlahti",
    coords: { lat: 61.073, lng: 28.137 },
    description: "Sammonlahti on suuri asuinalue Lappeenrannan pohjoispuolella. Alue tarjoaa hyvät palvelut ja bussiyhteydet keskustaan.",
    metaTitle: "Sammonlahti Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Sammonlahden bussien aikataulut. Lappeenrannan pohjoinen asuinalue.",
    type: "residential",
  },
  {
    slug: "lauritsala",
    citySlug: "lappeenranta",
    name: "Lauritsala",
    coords: { lat: 61.0715, lng: 28.2635 },
    description: "Lauritsala on itäinen kaupunginosa, entinen teollisuusalue Saimaan kanavan varrella. UPM:n tehdas on alueen suurin työnantaja.",
    metaTitle: "Lauritsala Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Lauritsalan bussien aikataulut. Lappeenrannan itäinen kaupunginosa.",
    type: "residential",
  },
  {
    slug: "joutseno",
    citySlug: "lappeenranta",
    name: "Joutseno",
    coords: { lat: 61.1172, lng: 28.508 },
    description: "Joutseno on entinen itsenäinen kunta, nykyään osa Lappeenrantaa. Alue sijaitsee idässä lähellä Imatran rajaa.",
    metaTitle: "Joutseno Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Joutsenon bussien aikataulut reaaliajassa. Lappeenrannan itäinen taajama.",
    type: "residential",
  },
  {
    slug: "satama",
    citySlug: "lappeenranta",
    name: "Satama",
    coords: { lat: 61.0508, lng: 28.1747 },
    description: "Lappeenrannan satama on suosittu kesäkohde Saimaan rannalla. Risteilylaivat lähtevät Saimaalle, ja alueella on ravintoloita.",
    metaTitle: "Lappeenrannan satama - Bussit reaaliajassa",
    metaDescription: "Katso Lappeenrannan sataman bussien aikataulut. Saimaan risteilyt.",
    type: "hub",
  },
  {
    slug: "armila",
    citySlug: "lappeenranta",
    name: "Armila",
    coords: { lat: 61.062, lng: 28.238 },
    description: "Armila on kaupallinen keskittymä Lappeenrannan itäosassa. Prisma ja muut liikkeet palvelevat laajaa aluetta.",
    metaTitle: "Armila Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Armilan kauppakeskuksen bussien aikataulut. Lappeenrannan ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "leiri",
    citySlug: "lappeenranta",
    name: "Leiri",
    coords: { lat: 61.082, lng: 28.17 },
    description: "Leiri on pohjoinen asuinalue Lappeenrannassa. Alue on rauhallinen ja hyvin bussiliikenteen saavutettavissa.",
    metaTitle: "Leiri Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Leirin bussien aikataulut reaaliajassa. Lappeenrannan pohjoinen alue.",
    type: "residential",
  },
  {
    slug: "kivisalmi",
    citySlug: "lappeenranta",
    name: "Kivisalmi",
    coords: { lat: 61.047, lng: 28.152 },
    description: "Kivisalmi on keskustan läheinen asuinalue Saimaan rannalla. Alue on suosittu rauhallisen sijaintinsa vuoksi.",
    metaTitle: "Kivisalmi Lappeenranta - Bussit reaaliajassa",
    metaDescription: "Katso Kivisalmen bussien aikataulut. Lappeenrannan keskustan lähialue.",
    type: "residential",
  },

  // Hämeenlinna - 10 stops
  {
    slug: "keskusta",
    citySlug: "hameenlinna",
    name: "Keskusta",
    coords: { lat: 60.9945, lng: 24.4642 },
    description: "Hämeenlinnan keskusta on historiallinen kaupunkikeskus Vanajaveden rannalla. Hämeenlinnan linna ja tori ovat alueen nähtävyyksiä.",
    metaTitle: "Hämeenlinnan keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Hämeenlinnan keskustan bussien aikataulut reaaliajassa. | Real-time buses in Hämeenlinna city center.",
    type: "hub",
  },
  {
    slug: "rautatieasema",
    citySlug: "hameenlinna",
    name: "Rautatieasema",
    coords: { lat: 60.9978, lng: 24.4602 },
    description: "Hämeenlinnan rautatieasema sijaitsee pääradalla Helsingin ja Tampereen välissä. Asemalta lähtee junia molempiin suuntiin tunnin välein.",
    metaTitle: "Hämeenlinnan rautatieasema - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Hämeenlinnan aseman bussien ja junien aikataulut.",
    type: "hub",
  },
  {
    slug: "kauriala",
    citySlug: "hameenlinna",
    name: "Kauriala",
    coords: { lat: 60.9768, lng: 24.4556 },
    description: "Kauriala on eteläinen asuinalue Hämeenlinnassa. Alue on rauhallinen ja perheystävällinen, ja bussit kulkevat keskustaan säännöllisesti.",
    metaTitle: "Kauriala Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Kaurialan bussien aikataulut. Hämeenlinnan eteläinen asuinalue.",
    type: "residential",
  },
  {
    slug: "tiirio",
    citySlug: "hameenlinna",
    name: "Tiiriö",
    coords: { lat: 60.9734, lng: 24.5031 },
    description: "Tiiriö on Hämeenlinnan itäinen kauppakeskittymä. Prisma ja muut liikkeet palvelevat laajaa asiakaskuntaa.",
    metaTitle: "Tiiriö Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Tiiriön kauppakeskuksen bussien aikataulut. Hämeenlinnan ostosalue.",
    type: "shopping",
  },
  {
    slug: "hattula",
    citySlug: "hameenlinna",
    name: "Hattula",
    coords: { lat: 61.0566, lng: 24.387 },
    description: "Hattula on naapurikunta Hämeenlinnan pohjoispuolella, tunnettu keskiaikaisesta kirkostaan. Bussit yhdistävät Hattulan Hämeenlinnaan.",
    metaTitle: "Hattula - Bussit reaaliajassa",
    metaDescription: "Katso Hattulan bussien aikataulut. Hämeenlinnan pohjoinen naapurikunta.",
    type: "residential",
  },
  {
    slug: "kantola",
    citySlug: "hameenlinna",
    name: "Kantola",
    coords: { lat: 61.004, lng: 24.487 },
    description: "Kantola on tapahtuma-alue ja asuinalue Hämeenlinnan itäpuolella. Kantolan tapahtumapuisto isännöi kesäisin konsertteja.",
    metaTitle: "Kantola Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Kantolan bussien aikataulut. Hämeenlinnan tapahtuma-alue.",
    type: "residential",
  },
  {
    slug: "kanta-hame-keskussairaala",
    citySlug: "hameenlinna",
    name: "Kanta-Häme keskussairaala",
    coords: { lat: 60.9853, lng: 24.493 },
    description: "Kanta-Hämeen keskussairaala on alueen pääterveydenhuoltoyksikkö. Bussit palvelevat sairaalaa ympäri vuorokauden.",
    metaTitle: "Kanta-Häme keskussairaala - Bussit reaaliajassa",
    metaDescription: "Katso Kanta-Hämeen keskussairaalan bussien aikataulut.",
    type: "hospital",
  },
  {
    slug: "ahvenisto",
    citySlug: "hameenlinna",
    name: "Ahvenisto",
    coords: { lat: 60.975, lng: 24.435 },
    description: "Ahvenisto on urheilukeskus ja asuinalue Hämeenlinnan lounaispuolella. Ahveniston moottorirata on tunnettu tapahtumakohde.",
    metaTitle: "Ahvenisto Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Ahveniston bussien aikataulut. Hämeenlinnan urheilukeskus.",
    type: "residential",
  },
  {
    slug: "jukola",
    citySlug: "hameenlinna",
    name: "Jukola",
    coords: { lat: 61.008, lng: 24.443 },
    description: "Jukola on pohjoinen asuinalue Hämeenlinnassa. Alue on kasvanut viime vuosina ja tarjoaa hyvät bussiyhteydet.",
    metaTitle: "Jukola Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Jukolan bussien aikataulut. Hämeenlinnan pohjoinen asuinalue.",
    type: "residential",
  },
  {
    slug: "katuma",
    citySlug: "hameenlinna",
    name: "Katuma",
    coords: { lat: 60.988, lng: 24.422 },
    description: "Katuma on läntinen asuinalue Hämeenlinnassa lähellä keskustaa. Alue on rauhallinen ja hyvin saavutettavissa.",
    metaTitle: "Katuma Hämeenlinna - Bussit reaaliajassa",
    metaDescription: "Katso Katuman bussien aikataulut. Hämeenlinnan läntinen asuinalue.",
    type: "residential",
  },

  // Pori - 10 stops
  {
    slug: "keskusta",
    citySlug: "pori",
    name: "Keskusta",
    coords: { lat: 61.4851, lng: 21.7975 },
    description: "Porin keskusta on Satakunnan pääkaupungin sydän. Kävelykatu ja tori ovat alueen keskipisteenä, ja bussit lähtevät keskustasta kaikkialle.",
    metaTitle: "Porin keskusta - Bussit reaaliajassa",
    metaDescription: "Katso Porin keskustan bussien aikataulut reaaliajassa. | Real-time buses in Pori city center.",
    type: "hub",
  },
  {
    slug: "matkakeskus",
    citySlug: "pori",
    name: "Matkakeskus",
    coords: { lat: 61.4807, lng: 21.7877 },
    description: "Porin matkakeskus yhdistää bussi- ja junaliikenteen. Asemalta lähtee junia Tampereelle ja busseja ympäri Satakuntaa.",
    metaTitle: "Porin matkakeskus - Bussit ja junat reaaliajassa",
    metaDescription: "Katso Porin matkakeskuksen bussien ja junien aikataulut.",
    type: "hub",
  },
  {
    slug: "puuvilla",
    citySlug: "pori",
    name: "Puuvilla",
    coords: { lat: 61.4889, lng: 21.8132 },
    description: "Puuvilla on entinen puuvillatehdas, nykyään kauppakeskus ja kulttuurikeskus. Alue yhdistää historiaa ja modernia elämää.",
    metaTitle: "Puuvilla Pori - Bussit reaaliajassa",
    metaDescription: "Katso Puuvillan kauppakeskuksen bussien aikataulut. Porin kulttuuri- ja ostoskeskus.",
    type: "shopping",
  },
  {
    slug: "sampola",
    citySlug: "pori",
    name: "Sampola",
    coords: { lat: 61.4799, lng: 21.7586 },
    description: "Sampola on läntinen kauppakeskittymä Porissa. Prisma ja muut liikkeet palvelevat laajaa asiakaskuntaa.",
    metaTitle: "Sampola Pori - Bussit reaaliajassa",
    metaDescription: "Katso Sampolan kauppakeskuksen bussien aikataulut. Porin läntinen ostosalue.",
    type: "shopping",
  },
  {
    slug: "lansi-pori",
    citySlug: "pori",
    name: "Länsi-Pori",
    coords: { lat: 61.497, lng: 21.745 },
    description: "Länsi-Pori on läntinen asuinalue lähellä merenrantaa. Alue on suosittu perheystävällisyytensä vuoksi.",
    metaTitle: "Länsi-Pori - Bussit reaaliajassa",
    metaDescription: "Katso Länsi-Porin bussien aikataulut. Porin läntinen asuinalue.",
    type: "residential",
  },
  {
    slug: "mantyluoto",
    citySlug: "pori",
    name: "Mäntyluoto",
    coords: { lat: 61.5922, lng: 21.4996 },
    description: "Mäntyluoto on Porin satama-alue ja entinen kalastuskylä. Alue on tärkeä teollisuus- ja satamatoiminnoille.",
    metaTitle: "Mäntyluoto Pori - Bussit reaaliajassa",
    metaDescription: "Katso Mäntyluodon sataman bussien aikataulut. Porin satama-alue.",
    type: "residential",
  },
  {
    slug: "pihlava",
    citySlug: "pori",
    name: "Pihlava",
    coords: { lat: 61.5574, lng: 21.5877 },
    description: "Pihlava on entinen teollisuusyhdyskunta Porin länsipuolella. Alue tunnetaan sahateollisuuden historiastaan.",
    metaTitle: "Pihlava Pori - Bussit reaaliajassa",
    metaDescription: "Katso Pihlavan bussien aikataulut. Porin läntinen taajama.",
    type: "residential",
  },
  {
    slug: "pormestarinluoto",
    citySlug: "pori",
    name: "Pormestarinluoto",
    coords: { lat: 61.495, lng: 21.829 },
    description: "Pormestarinluoto on itäinen asuinalue Porissa Kokemäenjoen varrella. Alue on rauhallinen ja luonnonläheinen.",
    metaTitle: "Pormestarinluoto Pori - Bussit reaaliajassa",
    metaDescription: "Katso Pormestarinluodon bussien aikataulut. Porin itäinen asuinalue.",
    type: "residential",
  },
  {
    slug: "satakunnan-keskussairaala",
    citySlug: "pori",
    name: "Satakunnan keskussairaala",
    coords: { lat: 61.4758, lng: 21.8101 },
    description: "Satakunnan keskussairaala on alueen pääterveydenhuoltoyksikkö. Bussit palvelevat sairaalaa säännöllisesti.",
    metaTitle: "Satakunnan keskussairaala - Bussit reaaliajassa",
    metaDescription: "Katso Satakunnan keskussairaalan bussien aikataulut. Porin sairaala.",
    type: "hospital",
  },
  {
    slug: "viasvesi",
    citySlug: "pori",
    name: "Viasvesi",
    coords: { lat: 61.508, lng: 21.775 },
    description: "Viasvesi on pohjoinen asuinalue Porissa. Alue on kasvanut viime vuosina ja tarjoaa hyvät palvelut.",
    metaTitle: "Viasvesi Pori - Bussit reaaliajassa",
    metaDescription: "Katso Viasveden bussien aikataulut. Porin pohjoinen asuinalue.",
    type: "residential",
  },
];

// Helper functions
export function getStopsByCity(citySlug: string): StopConfig[] {
  return STOPS.filter((stop) => stop.citySlug === citySlug);
}

export function getStopBySlug(citySlug: string, stopSlug: string): StopConfig | undefined {
  return STOPS.find((stop) => stop.citySlug === citySlug && stop.slug === stopSlug);
}

export function getAllStopParams(): { city: string; stop: string }[] {
  return STOPS.map((stop) => ({ city: stop.citySlug, stop: stop.slug }));
}
